// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1,2,3,5,8,13,21,34,55,89,...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.


int firstNumber = 0;
int secondNumber = 1;
int sumOfEvenNumbers = 0;

for (int i = 0; i < 100; i++)
{
    int som = firstNumber + secondNumber;
    firstNumber = secondNumber;
    secondNumber = som;
    Console.WriteLine(som);

    if (som % 2 == 0)
    {
        int evenNumbers;
        evenNumbers = som;
        sumOfEvenNumbers += evenNumbers;
    }

    if (som >= 4000000)
    {
        break;
    }

}
Console.WriteLine(sumOfEvenNumbers);
